[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["lib/cairo-contracts/src"]

[contracts]
StarkInu = ["src/StarkInu.cairo"]
StarkPay = ["src/StarkPay.cairo"]

[format]
target = ["src", "tests"]
ignore-broken = true

[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"
chain-id = 1536727068981429685321

# https://github.com/Shard-Labs/starknet-devnet
["profile.devnet.protostar.deploy"]
gateway-url="http://127.0.0.1:5050/"

["profile.testnet.protostar.deploy"]
network="testnet"

["profile.mainnet.protostar.deploy"]
network="mainnet"